###
//GetAllPosts
GET http://localhost:3000/post
###
POST http://localhost:3000/post
Content-Type: application/json
{
  "title": "Traviling to Japan and dubai", 
  "senderID": "user123"
}
###

###
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Vacation On the Beach, Miconos", 
  "senderID": "user456"
}
###

###
//GetPostById
GET  http://localhost:3000/post/691b2c1ef901c3ee5767d7c2
###

###
//GetPostBySender
GET http://localhost:3000/post?senderID=user456
###

###
//GetAllPosts
GET http://localhost:3000/post
###
//UpdatePost
PUT http://localhost:3000/post/691b2c1ef901c3ee5767d7c2
Content-Type: application/json

{
  "title": "Updated Title: Trip to Paris",
  "senderID": "MamaMia"
}


