###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?releaseYear=2010

###

GET http://localhost:3000/post/69133c28251f35bcbc4206a6


###

POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Inception",
  "releaseYear": 2010
}

###

DELETE http://localhost:3000/post/69133c28251f35bcbc4206a6

###

PUT http://localhost:3000/post/69133cc67e0a6f1ddc7f1ec7
Content-Type: application/json

{
  "title": "Star Wars",
  "releaseYear": 1999
}


